gcc main.c -o main
./main PositionTransformMicrocodeA > gens/PositionTransformMicrocodeA.mem
./main PositionTransformMicrocodeB > gens/PositionTransformMicrocodeB.mem
./main PositionTransformMicrocodeC > gens/PositionTransformMicrocodeC.mem
./main NormalTransformMicrocodeA > gens/NormalTransformMicrocodeA.mem
./main NormalTransformMicrocodeB > gens/NormalTransformMicrocodeB.mem
./main NormalTransformMicrocodeC > gens/NormalTransformMicrocodeC.mem
./main TexcoordTransformMicrocodeA > gens/TexcoordTransformMicrocodeA.mem
./main TexcoordTransformMicrocodeB > gens/TexcoordTransformMicrocodeB.mem
./main TexcoordTransformMicrocodeC > gens/TexcoordTransformMicrocodeC.mem
