#pragma once

#include "Instruction.h"

const uint16_t NormalTransformMicrocodeA[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	PT_OPERATION(OP_READY)                                                                         // 5
};

const uint16_t NormalTransformMicrocodeB[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 1), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 1), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(5), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 1), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(5), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	PT_OPERATION(OP_READY)                                                                         // 5
};

const uint16_t NormalTransformMicrocodeC[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 2), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 2), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(9), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 2), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(9), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	PT_OPERATION(OP_READY)                                                                         // 5
};