#pragma once

#include "Instruction.h"

const uint16_t TexcoordTransformMicrocodeA[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	INSTRUCTION(PTA_ACCUMULATOR(0), PTB_MATRIX(3, 0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)),   // 5
	PT_OPERATION(OP_READY)                                                                         // 6
};

const uint16_t TexcoordTransformMicrocodeB[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	INSTRUCTION(PTA_ACCUMULATOR(0), PTB_MATRIX(3, 0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)),   // 5
	PT_OPERATION(OP_READY)                                                                         // 6
};

const uint16_t TexcoordTransformMicrocodeC[] = {
	// Vec3 Multiply By 3x4 Matrix
	INSTRUCTION(PTA_VECTOR(0), PTB_MATRIX(0, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(0)),       // 0
	INSTRUCTION(PTA_VECTOR(1), PTB_MATRIX(1, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 1
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 2
	INSTRUCTION(PTA_VECTOR(2), PTB_MATRIX(2, 0), PT_OPERATION(OP_MULT), PTU_ACCUMULATOR(1)),       // 3
	INSTRUCTION(PTA_ACCUMULATOR(1), PTB_ACCUMULATOR(0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)), // 4
	INSTRUCTION(PTA_ACCUMULATOR(0), PTB_MATRIX(3, 0), PT_OPERATION(OP_ADD), PTU_ACCUMULATOR(0)),   // 5
	PT_OPERATION(OP_READY)                                                                         // 6
};